name: "jaffle_shop_last"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

# New default is dbt_packages (dbt_modules is deprecated)
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"  # keep for cleanup if you used older dbt versions

models:
  jaffle_shop_last:
    staging:
      +materialized: view
    marts:
      +materialized: table